from django.db import models

# Create your models here.
from django.db import models

class MusicFile(models.Model):
    title = models.CharField(max_length=200)
    artist = models.CharField(max_length=200)
    # Fields for the recognition function's data (e.g., a unique hash)
    # This is a pre-calculated string generated by the recognition component.
    fingerprint = models.TextField(unique=True)

    class Meta:
        # If your teammate's table has a specific name, you can define it here.
        # Example if the table is named 'song_catalog':
        # db_table = 'song_catalog'
        pass

    def __str__(self):
        return f"{self.artist} - {self.title}"
pass